export const FORM_TEXT = {
  en: {
    title: "Contact Us",
    subtitle: "Send us a message",
    description: "Have questions? Answers are just a message away. Complete the form below to contact our global headquarters.",
    joinUs: "Join Us",
    headline1: "Discover a world" ,
    headline2: "where technology is",
    headline3: "synonymous with trust",
    subHeadline: ['Fill out the form below to receive our newsletter, important updates,',' and information about our services directly in your inbox.'],
    firstName: "First Name",
    lastName: "Last Name",
    jobTitle: "Job Title",
    companyName: "Company Name",
    email: "Email",
    phoneNumber: "Phone Number",
    message: "Message",
    interestsLabel: "Please select your interests",
    interests: {
      companyNews: "Company News",
      counterfeitDetection: "Counterfeit Detection",
      failureAnalysis: "Failure Analysis",
      lifecycle: "Lifecycle & Reliability",
      logistics: "Logistics",
      programming: "Programming",
      factoryAuditing: "Factory Auditing",
      training: "Training",
    },
    submitButton: "Submit",
  },
  de: {
    title: "Kontaktieren Sie uns",
    subtitle: "Senden Sie uns eine Nachricht",
    description: "Haben Sie Fragen? Antworten sind nur eine Nachricht entfernt. Füllen Sie das Formular unten aus, um unser globales Hauptquartier zu kontaktieren.",
    joinUs: "Begleiten Sie uns",
    headline1: "Entdecken Sie eine Welt",
    headline2: "in der Technologie",
    headline3: "gleichbedeutend mit Vertrauen ist",
    subHeadline: [
      "Füllen Sie das untenstehende Formular aus, um unseren Newsletter, wichtige Updates",
      " und Informationen über unsere Dienstleistungen direkt in Ihrem Posteingang zu erhalten."
    ],
    firstName: "Vorname",
    lastName: "Nachname",
    jobTitle: "Berufsbezeichnung",
    companyName: "Firmenname",
    email: "E-Mail",
    phoneNumber: "Telefonnummer",
    message: "Nachricht",
    interestsLabel: "Bitte wählen Sie Ihre Interessen",
    interests: {
      companyNews: "Unternehmensnachrichten",
      counterfeitDetection: "Fälschungserkennung",
      failureAnalysis: "Fehleranalyse",
      lifecycle: "Lebenszyklus & Zuverlässigkeit",
      logistics: "Logistik",
      programming: "Programmierung",
      factoryAuditing: "Fabriküberprüfung",
      training: "Schulung",
    },
    submitButton: "Senden",
  },
  cn: {
    title: "联系我们",
    subtitle: "发送信息",
    description: "有疑问？答案只需发送一条消息即可。请填写以下表格以联系我们的全球总部。",
    joinUs: "加入我们",
    headline1: "发现一个世界",
    headline2: "在这里，技术",
    headline3: "与信任同义",
    subHeadline: [
      "填写以下表格，接收我们的新闻通讯、重要更新",
      " 以及关于我们服务的信息，直接发送到您的收件箱。"
    ],  
    firstName: "名字",
    lastName: "姓氏",
    jobTitle: "职位",
    companyName: "公司名称",
    email: "电子邮件",
    phoneNumber: "电话号码",
    message: "信息",
    interestsLabel: "请选择您的兴趣",
    interests: {
      companyNews: "公司新闻",
      counterfeitDetection: "假货检测",
      failureAnalysis: "故障分析",
      lifecycle: "生命周期与可靠性",
      logistics: "物流",
      programming: "编程",
      factoryAuditing: "工厂审核",
      training: "培训",
    },
    submitButton: "提交",
  },
};
